export type Locale = "en" | "ar";

export const APP_NAME = "CAVO";
export const DEFAULT_THEME = "dark" as const;
export const DEFAULT_LOCALE = "en" as const;

export const labels = {
  en: {
    home: "Home",
    categories: "Categories",
    offers: "Offers",
    links: "Links",
    cart: "Cart",
    account: "Account",
    videos: "Videos",
    featured: "Featured drops",
    hotOffers: "Hot offers",
    premiumSubtitle: "Premium mirror-quality footwear.",
    heroTitle: "Black and gold, built like a real app.",
    heroText: "Fast shopping flow, clean product details, and luxury visuals tuned for mobile.",
    browse: "Browse now",
    openLinks: "Open links",
    size: "Size",
    color: "Color",
    category: "Category",
    stock: "Stock",
    afterDiscount: "After discount",
    beforeDiscount: "Before discount",
    addToCart: "Add to cart",
    continueShopping: "Continue shopping",
    emptyCart: "Your cart is empty",
    emptyCartText: "Pick your next pair and keep the cart ready.",
    authTitle: "Sign in",
    authText: "Login methods will be connected later. This version focuses on clean app UX.",
    accountTitle: "Account",
    accountText: "Profile, orders, language, and support all live here.",
    comingSoon: "Coming soon",
    linksTitle: "Quick links",
    linksText: "Every official CAVO channel in one premium place.",
    kids: "Kids",
    men: "Men",
    women: "Women",
    website: "Website",
    whatsapp: "WhatsApp",
    telegram: "Telegram",
    instagram: "Instagram",
    facebook: "Facebook",
    tiktok: "TikTok",
    viewAll: "View all",
    related: "You may also like",
    qty: "Qty",
    login: "Login",
    support: "Support",
    shipping: "Shipping inside Hurghada only",
    language: "Language",
    theme: "Theme",
    darkDefault: "Dark default",
  },
  ar: {
    home: "الرئيسية",
    categories: "الأقسام",
    offers: "العروض",
    links: "الروابط",
    cart: "السلة",
    account: "الحساب",
    videos: "الفيديوهات",
    featured: "مختارات مميزة",
    hotOffers: "عروض قوية",
    premiumSubtitle: "أحذية ميرور كواليتي بإحساس فاخر.",
    heroTitle: "أسود وذهبي بإحساس تطبيق حقيقي.",
    heroText: "تجربة تسوق سريعة، صفحة منتج أنضف، وهوية فخمة معمولة للموبايل.",
    browse: "ابدأ التصفح",
    openLinks: "الروابط",
    size: "المقاس",
    color: "اللون",
    category: "القسم",
    stock: "المتوفر",
    afterDiscount: "بعد الخصم",
    beforeDiscount: "قبل الخصم",
    addToCart: "أضف للسلة",
    continueShopping: "كمل التصفح",
    emptyCart: "السلة فاضية",
    emptyCartText: "اختار الموديل المناسب وخليه جاهز في السلة.",
    authTitle: "تسجيل الدخول",
    authText: "طرق التسجيل هتتربط بعدين. النسخة دي مركزة على الشكل والتجربة.",
    accountTitle: "الحساب",
    accountText: "الملف، الطلبات، اللغة، والدعم في مكان واحد.",
    comingSoon: "قريبًا",
    linksTitle: "روابط سريعة",
    linksText: "كل قنوات CAVO الرسمية في مكان واحد.",
    kids: "أطفال",
    men: "رجالي",
    women: "حريمي",
    website: "الموقع",
    whatsapp: "واتساب",
    telegram: "تليجرام",
    instagram: "إنستجرام",
    facebook: "فيسبوك",
    tiktok: "تيك توك",
    viewAll: "عرض الكل",
    related: "قد يعجبك أيضًا",
    qty: "الكمية",
    login: "دخول",
    support: "الدعم",
    shipping: "الشحن داخل الغردقة فقط",
    language: "اللغة",
    theme: "الثيم",
    darkDefault: "الدارك افتراضي",
  }
} as const;
